### ISSUE TITLE
Pull environmental covariates script 

### ISSUE THREAD

**Issue by ErinCain** [SRJPE/SRJPEdata#12]
All work done in `env-data` branch
Create a script to pull updated environmental gage data for each tributary (utilize logic from jpe-datasets)
Check that queries return data 
Updates existing data with new data from query (make sure to use old data if new query fails) 
Cache data as an environmental_gage.rds table. 
Environmental gage should have date, stream, site, site_group, environmental parameter (flow, temp), value, unit, gage agency, gage number, and statistic)

**Comment by alvizek** [comment]
Tracking notes about decisions:

- There is quite a bit of analysis code related to interpolating missing values for Feather and Yuba. Decided to move this to a separate Rmd in the analysis folder (https://github.com/SRJPE/JPE-datasets/blob/covariate-processing/analysis/water_temp_regression.Rmd). This is on the covariate-processing branch currently and will be merged into main soon.
- For Yuba and Feather in the pull script, lets save these datasets with the interpolation in the package (see the Rmd for where they are saved in GCP) AND pull in data from the gages but filter to year(date) > 2024. That way we do not need to apply all the regression interpolation within the package. The data with interpolation will represent the "historical dataset" and then we will rely on the gages moving forward.
