### ISSUE TITLE
create observed_adult_inputs.Rds

### ISSUE THREAD

**Issue by ErinCain** [SRJPE/SRJPEdata#13]
Review lucid - https://lucid.app/lucidchart/18b732f1-a2e3-433b-a56d-3dc8fd6b1cf6/edit?invitationId=inv_9eaeb578-6303-4b54-855c-55a0d520ea90&page=Ju.de5gHoc_C# 

Create adult table that can be used to pass to P2S or used directly by stock recruit. 

Initial data prep for this table is in `data-raw/build_adult_model_datasets.R`

- [x] document

**Comment by ErinCain** [comment]
Added to wip branch

**Comment by liz-fw** [comment]
documentation added to wip branch

**Comment by ErinCain** [comment]
I think this is done so closing issue.
