### ISSUE TITLE
check many many error when build rst datasets

### ISSUE THREAD

**Issue by alvizek** [SRJPE/SRJPEdata#35]
Warning messages:
1: In full_join(weekly_standard_catch_unmarked, weekly_hours_fished) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 3 of `x` matches multiple rows in `y`.
ℹ Row 17015 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
2: In left_join(environmental_data, site_lookup) :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 1 of `x` matches multiple rows in `y`.
ℹ Row 1 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.

**Comment by ErinCain** [comment]
For warning 1: Looks like warning message one is occurring because `weekly_standard_catch_unmarked` does not have a subsite column. There are a few different weekly standard catch files so confirming that this is the one that we want for this table and then will resolve the subsite issue.

**Comment by ErinCain** [comment]
For warning 2: a many many join makes sense. 
Row 1 of x environment only has stream and site group so we intend to map it to many rows of y (to generate environmental data for all rows) 
Row 1 of y site will then be mapped to multiple statistics of environmental (mean, min, and max) causing a many many join the other way.

**Comment by ErinCain** [comment]
warning 1. looks like table produced from join is not required / used later in the script/ removing this logic in `addresses-issues` branch.

**Comment by ErinCain** [comment]
Warning 2: added relationship = `many-to-many` to silence warning.
