### ISSUE TITLE
check warning - when run build_rst_model_datasets

### ISSUE THREAD

**Issue by alvizek** [SRJPE/SRJPEdata#38]
Get this warning - check to make sure these are being removed or handled appropriately

3: In .f(.x[[i]], ...) :
  The data for live oak in 2002 only goes to 2 and should not be used as a full season.
4: In .f(.x[[i]], ...) :
  The data for shawn's beach in 2009 only goes to 1 and should not be used as a full season.
5: In .f(.x[[i]], ...) :
  The data for gateway riffle in 2016 only goes to 16 and should not be used as a full season.

**Comment by ErinCain** [comment]
Getting new warning messages - 
Warning messages:
1: In .f(.x[[i]], ...) :
  The data for lbc in 2016 only goes to 11 and should not be used as a full season.
2: In max(filtered_data$run_year) :
  no non-missing arguments to max; returning -Inf
3: In max(pull(filter(filtered_data, run_year == max_year, week < 45),  :
  no non-missing arguments to max; returning -Inf
4: In .f(.x[[i]], ...) :
  The data for NA in -Inf only goes to -Inf and should not be used as a full season.

Digging into these...

**Comment by ErinCain** [comment]
There is one NA site in weekly_juvenile abundance data that is associated with battle creek. Did this come from the new EDI data?

**Comment by ErinCain** [comment]
In terms of battle creek 2016 warning. The original data we had shows sampling at battle creek for all of 2016. I wonder if this could also be a data update thing? If so I can add to our years to exclude table. <img width="1369" alt="Screenshot 2024-08-28 at 10 20 54 AM" src="https://github.com/user-attachments/assets/4b51f1d9-affd-422a-a31d-54f7d6307efd">
