### ISSUE TITLE
Keep month in environmental data

### ISSUE THREAD

**Issue by liz-fw** [SRJPE/SRJPEdata#62]
We summarize by week and year in `data-raw/pull_data_scripts/pull_environmental_data.R` but we need `month` for the summarization we do in `prep_environmental_covariates.Rmd`. Can we modify the pull script to keep month?

**Comment by ErinCain** [comment]
I added a fix for this in the years to exclude PR.

**Comment by ErinCain** [comment]
Although looks like we will have to make some additional updates to the temp vignettes to make sure that they do not call on date column
